# Generated by Django 5.2.4 on 2025-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(to='core.service'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subservice_images/'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
